import Head from 'next/head'
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import Aos from 'aos';
import 'aos/dist/aos.css';
import { useEffect, useState } from 'react';

export default function Home() {
  useEffect(() => {
    Aos.init({ duration: 1500 });
  }, [])

  let [skill, setSkill] = useState("")

  let skills = () => {
    if (skill === "") {
      return <>/* clique sobre o ícone para ler as informações.*/</>
    } else if (skill === "css") {
      return <div className={styles.boxSkill1}>
        <h4>CSS</h4>
        <p className={styles.textSkill}>Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web, aplicado diretamente nas tags HTML ou ficar contido dentro das tags.</p>
        <p className={styles.textSkill}>Tenho mais de 1 ano e meio de experiência com esta tecnologia.</p>

      </div>

    } else if (skill === "html") {
      return <div className={styles.boxSkill2}>
        <h4>HTML</h4>
        <p className={styles.textSkill}>HTML é uma linguagem de marcação utilizada na construção de páginas na Web.</p>
        <p className={styles.textSkill}>Tenho mais de 1 ano e meio de experiência com esta tecnologia.</p>

      </div>

    } else if (skill === "js") {
      return <div className={styles.boxSkill3}>
        <h4>Javascript</h4>
        <p className={styles.textSkill}>JavaScript é uma linguagem de programação interpretada estruturada, de script em alto nível com tipagem dinâmica fraca e multiparadigma. Juntamente com HTML e CSS, o JavaScript é uma das três principais tecnologias da World Wide Web</p>
        <p className={styles.textSkill}>Tenho mais de 1 ano e meio de experiência com esta tecnologia.</p>

      </div>
    } else if (skill === "node") {
      return <div className={styles.boxSkill4}>
        <h4>Node</h4>
        <p className={styles.textSkill}>Node.js é um software de código aberto, multiplataforma, baseado no interpretador V8 do Google e que permite a execução de códigos JavaScript fora de um navegador web.</p>
        <p className={styles.textSkill}>Tenho mais de 1 ano de experiência com esta tecnologia.</p>

      </div>
    } else if (skill === "next") {
      return <div className={styles.boxSkill5}>
        <h4>Next.js</h4>
        <p className={styles.textSkill}>Next.js é uma estrutura da web de desenvolvimento front-end React de código aberto criada por Vercel que permite funcionalidades como renderização do lado do servidor e geração de sites estáticos para aplicativos da web baseados em React.</p>
        <p className={styles.textSkill}>Tenho mais de 6 meses de experiência com esta tecnologia.</p>

      </div>
    } else if (skill === "react") {
      return <div className={styles.boxSkill6}>
        <h4>React</h4>
        <p className={styles.textSkill}>O React é uma biblioteca front-end JavaScript de código aberto com foco em criar interfaces de usuário em páginas web.</p>
        <p className={styles.textSkill}>Tenho mais de 1 ano e meio de experiência com esta tecnologia.</p>

      </div>
    }

  }

  return (
    <div className={styles.portfolio}>
      <script>
      </script>
      <Head>
        <title>Portfólio // Christopher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/rosto.png" />
      </Head>
      <header className={styles.navBar}>
        <div className={styles.logo}>
          <div className={styles.logoStyle1}>
            <div className={styles.logoStyleCenter1}></div>
            <div className={styles.letter}>C</div>
          </div>

          <div className={styles.logoStyle2}>
            <div className={styles.logoStyleCenter2}></div>
            <div className={styles.letter}>F</div>
          </div>

          <div className={styles.logoStyle3}>
            <div className={styles.logoStyleCenter3}></div>
            <div className={styles.letter}>S</div>
          </div>
        </div>

        <nav className={styles.btns}>
          <a className={styles.btn} href='#inicio'>Início</a>
          <a className={styles.btn} href='#about'>Quem Sou</a>
          <a className={styles.btn} href='#projects'>Projetos</a>
          <a className={styles.btn} href='#habilities'>Habilidades</a>
          <a className={styles.btn} href='#tools'>Ferramentas</a>
        </nav>
      </header>

      <main id="inicio" className={styles.main}>
        <div className={styles.boxLeft}>
          <div>Oi, eu sou</div>
          <div className={styles.name}>
            Christopher <div className={styles.red}>Feilstrecker</div> da Silva.
            <div className={styles.line}></div>
          </div>
          <div className={styles.typingBox}>
            <div className={styles.typing}>Desenvolvedor Web Fullstack</div>

          </div>

          <div className={styles.btnsSocialMidia}>
            <a href="https://www.linkedin.com/in/christopher-feilstrecker/" target="_blank" rel="noreferrer"><div className={styles.btnSocialMidia}>Linkedin</div></a>
            <a href="https://github.com/ChristpherFeilstrecker" target="_blank" rel="noreferrer"><div className={styles.btnSocialMidia}>Github</div></a>
          </div>
        </div>

        <div className={styles.boxRigth}>
          <Image className={styles.rosto} src='/images/rosto.png' width="300" height='300' alt='icone rosto' />
        </div>

      </main>

      <about id="about" className={styles.aboutContainer}>

        <div data-aos="fade-right" className={styles.aboutboxLeft}>
          <Image className={styles.foto} src='/images/foto.jfif' width="350" height='350' alt='rosto' />

          <div className={styles.logo_2}>

            <div className={styles.logoStyle2_2}>
              <div className={styles.logoStyleCenter2_2}></div>
              <div className={styles.letter}>JS</div>
            </div>

            <div className={styles.logoStyle1_2}>
              <div className={styles.logoStyleCenter1_2}></div>
              <div className={styles.letter}>5</div>
            </div>

            <div className={styles.logoStyle3_2}>
              <div className={styles.logoStyleCenter3_2}></div>
              <div className={styles.letter}>3</div>
            </div>
          </div>
        </div>

        <div data-aos="fade-left" className={styles.aboutboxRigth}>

          <div className={styles.title}><h1> Quem Sou </h1><h1 className={styles.red}> .</h1></div>

          <div>
            Meu nome é Christopher F. da Silva, sou apaixonado por tecnologia. Meu primeiro contato com programação foi em 2021 quando decidi mudar de carreira e um amigo me apresentou o desenvolvimento web.
          </div>
          <br />
          <div className={styles.textLabenu}>
            Iniciei meus estudos participando do bootcamp da  <a className={styles.btnLabenu} href="https://www.labenu.com.br/" target="_blank" rel="noreferrer">Labenu</a> para desenvolvedor web fullstack, com aulas diárias e projetos semanais, executando mais de 30 projetos durante todo curso.
          </div>

          <br />
          <div>
            Atualmente sou freelancer como desenvolvedor fullstack, criando desde o layout até a manutenção do site no servidor.
          </div>

        </div>
      </about>

      <projetcts id="projects" className={styles.projectsContainer}>
        <div className={styles.title}><h1> Projetos </h1><h1 className={styles.red}> .</h1></div>

        <div className={styles.projectContainerTop}>

          <div className={styles.projectBoxLeft}>
            <h2>Pokenext</h2>

            <div className={styles.projectText}>Site de lista de pokemons, feito em Next.js, Javascript e styled-components.</div>

            <div className={styles.projectBtnsContainer}>
              <h3 className={styles.projectBtnLeft}>Documentação</h3>
              <h3 className={styles.projectBtnLeft}>Visualizar projeto</h3>
            </div>

          </div>

          <div className={styles.projectBoxRight}>
            <h2>Labefood</h2>

            <div className={styles.projectText}>Projeto final do bootcamp da labenu, feito em React, Javascript e CSS.</div>

            <div className={styles.projectBtnsContainer}>
              <h3 className={styles.projectBtnRight}>Documentação</h3>
              <h3 className={styles.projectBtnRight}>Visualizar projeto</h3>
            </div>
          </div>
        </div>

        <div className={styles.projectBoxBottom}>
        <h2>Aggostini</h2>

<div className={styles.projectText}>Site para empresa de produtos e serviços hidráulicos, feito com React, Node e Javascript</div>

<div className={styles.projectBtnsContainer}>
  <h3 className={styles.projectBtnBottom}>Documentação</h3>
  <h3 className={styles.projectBtnBottom}>Visualizar projeto</h3>
</div>
        </div>

        <div></div>

        <div className={styles.boxbtnMore}>
          <div className={styles.btnMore}>Repositórios Github</div>

        </div>
      </projetcts >

      <habilities id="habilities" className={styles.habilitiesContainer}>

      <div className={styles.title}><h1> Habilidades </h1><h1 className={styles.red}> .</h1></div>

        <div className={styles.habBoxContainer}>
          <div data-aos="fade-right" className={styles.habLeftBox}>

            <Image onClick={() => setSkill("js")} className={styles.fotohabilities} src='/images/javascripticon.png' width="150" height='180' alt='javascripticon' />
            <Image onClick={() => setSkill("html")} className={styles.fotohabilities} src='/images/htmlicon.png' width="150" height='180' alt='htmlicon' />
            <Image onClick={() => setSkill("css")} className={styles.fotohabilities} src='/images/cssicon.png' width="150" height='180' alt='cssicon' />
            <Image onClick={() => setSkill("node")} className={styles.fotohabilities} src='/images/nodeicon.png' width="150" height='150' alt='nodeicon' />
            <Image onClick={() => setSkill("next")} className={styles.fotohabilities} src='/images/nexticon.png' width="150" height='150' alt='nexticon' />
            <Image onClick={() => setSkill("react")} className={styles.fotohabilities} src='/images/reacticon.png' width="150" height='150' alt='reacticon' />

          </div>

          <div data-aos="fade-left" className={styles.habRigthBox}>
            {skills()}
          </div>

        </div>

      </habilities>

      <footer className={styles.footerContainer}>

        <div className={styles.footerCollumn}>
          <div className={styles.footerBox}>
            <Image className={styles.footericon} src='/images/emailicon.png' width="50" height='50' alt='reacticon' />
            christopher.feilstrecker@gmail.com
          </div>

          <div className={styles.footerBox}>
            <Image className={styles.footericon} src='/images/phoneicon.png' width="50" height='50' alt='reacticon' />
            +55 (51) 98947-7910
          </div>

          <div className={styles.footerBox}>
            <Image className={styles.footericon} src='/images/addressicon.png' width="50" height='50' alt='reacticon' />
            Rolante/RS
          </div>
        </div>

        <div className={styles.footerCollumn}>
          <a href="https://github.com/ChristpherFeilstrecker" target="_blank" rel="noreferrer">
            <Image className={styles.footericon} src='/images/githubicon.png' width="50" height='50' alt='reacticon' />
          </a>
          <a href="https://www.linkedin.com/in/christopher-feilstrecker/" target="_blank" rel="noreferrer">
            <Image className={styles.footericon} src='/images/linkedinicon.png' width="50" height='50' alt='reacticon' />

          </a>

        </div>


      </footer>
    </div>
  )
}
